### ISSUE TITLE
Suggestion for Change to Add-on Configuration Tab

### ISSUE THREAD

**Issue by BrettEBowman** [lavinir/hassio-onedrive-backup#122]
I recently updated to v2.2 with the new configuration method. I read the release notes about the changes to configuration and that the previous settings would (hopefully) be migrated, but should be verified. After starting the add-on, I monitored the log and saw that it says the new settings file wasn't found so it was using the legacy settings. So far, so good. Then I went to the add-on's "Configuration" tab, and got a basically blank screen:
![Screenshot 2023-10-04 103450](https://github.com/lavinir/hassio-onedrive-backup/assets/17341309/8712c82e-d978-4a8c-a8ad-df4a734307db)
I then used the 3 dots menu to change to "Edit in YAML" mode. Then the contents of my old settings were displayed in the Options section. But I was confused because whenever I went back to "Edit in UI" mode, none of the settings seemed to be migrated/displayed. Tried hard refresh, etc. Nothing seemed to help. The log did seem to indicate that the add-on was running and it do a backup to OneDrive.

After seeing another post here, I noticed the add-on's new "Web UI" showing the backups. That's when it finally hit me: the configuration settings had been moved from the HA Add-on "Configuration" tab to a tab in the new UI!

So, my suggestion is (if possible) to modify the add-on "Configuration" page to direct the user to the "Open Web UI" link on the Info tab for add-on settings. And, ideally, to also open display the old settings labeled something like "For reference: Legacy settings were:" or something and show the YAML view listing all of the old settings. That would aid in verifying/correcting the migrated settings.

**Comment by lavinir** [comment]
Hi, so about the new settings location, this was mentioned in the release notes but the migration handling was a bad call on my part. It's interesting that you see the old settings in the yaml because if those exist the addon should have been able to pull them.

When you load the addon UI it also pops up a new message explaining configuration is now done in the settings tab. To put a reference in the config would be kind of 'hacky' because I would have to put actual configuration properties inside that section and it is populated by Home Assistant automatically. 

I think not having any config options would mostly confuse existing users but hopefully just once :)
