### ISSUE TITLE
missing full backups

### ISSUE THREAD

**Issue by Tom-Heitbrink** [lavinir/hassio-onedrive-backup#143]
I've noticed that the onedrive backup is not making a full if a partial backup is done in the last 24 hours. 
This is likely related to the lasat datetime a backup was created, and the absence of a scheduled backup. 
I understand that the solution for a fixed moment of backup is that you state to only make backups at a given moment, but this prevents the creation of partial backups when an update is installed. In that case I would like the backup to be made before the installation.
Is it possible to set a default time that a backup should be run, and still have the partials be done whenever they are needed ? 

If not, then I suggest that the full backup is looking at the date and time the last full backup was made, instead of only the last backup. 

See screenshot.
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/88239288/a79a9e36-b8ca-43db-9414-bd82f3e56cc6)

**Comment by lavinir** [comment]
This is something I thought about in the past and haven't decided on the best way to handle yet. For HA upgrade backups, you can choose to ignore them in the settings and then you still have local copies of those and it won't impact the regular scheduled backups. Are these the backups you are looking to ignore ?

However, consider you main backup settings exclude a certain addon or folder - by definition they are not "partial" backups. In that case all backups are "partial" and there are no 'full' backups.

**Comment by Tom-Heitbrink** [comment]
I'm not sure I understand, I want homeassistant to make full backups daily, and the partiasl backups are for the backups requested by upgrades of addons. They are also marked full or partial by the onedrive logic, so I don't understand why you state that there are no full backups. I have no exclusions in the backup settings. 
For now I'll try to ignore the upgrade backups.

**Comment by lavinir** [comment]
What I meant is, that some people set up their backups to ignore a folder (e.g. media) or ignore an addon that takes a lot of storage space. If anything like that is excluded then the backups are "partial" backups. 
These "partial" backups, are supposed to be treated as the user's regular "full" backup and are not the same as the Home Assistant addon upgrade backups. 

So if you want to just ignore those update backups, that toggle will suffice. Otherwise, more complex logic would need to be implemented.

**Comment by codemunkie15** [comment]
I am also missing full daily backups due to this I think. If there are no plans to implement a fix, at least mentioning it in the docs could be useful?

IMO if I have configured a full backup every day, this is how it should work regardless of partials.

**Comment by lavinir** [comment]
Want to make sure we are talking about the same thing. 
If you aren't telling the addon to ignore Home Assistant backup upgrades then in case you upgraded an addon it would count towards your regular backups. And so long as such a backup exists within the defined backup interval, no new backup will be automatically triggered. 

"Partials" is confusing here because it's enough for you to omit one of the folder for backup (e.g. Media) or one of the addons for the backup to be classified as "Partial. In that scenario, those are you regular "full" backups and if one of those already exists the add on should not trigger a daily backup for that day.

The only thing I think may be an acceptable here, is to try to identify the backup as an addon upgrade backup (even when you are choosing not to ignore them) but ignore it in terms of looking for the most recent 'watched' backup.

**Comment by codemunkie15** [comment]
> The only thing I think may be an acceptable here, is to try to identify the backup as an addon upgrade backup (even when you are choosing not to ignore them) but ignore it in terms of looking for the most recent 'watched' backup.

I agree with this. In my opinion, backups created by this integration via the schedule should be completely separate from manual/upgrade backups. Even if I do a manual full backup myself one day, the schedule for the automated backup should still execute. Nothing happening outside of the integration should affect the scheduled backups that you define.

**Comment by lavinir** [comment]
I'm not sure this is as clear cut as you say. The addon either lives in a vacuum or it doesn't. You can set it up as the former and it would do exactly that. If you opt in to monitoring all backups (Ignoring for a minute the issue with upgrade backups), I would expect the backup quotas to be honored still, otherwise, what does it mean to monitor them?
