### ISSUE TITLE
Sensors Missing After Upgrade to 2022.11.5 - Required Restart of the Add-on to Restore

### ISSUE THREAD

**Issue by ziptbm** [lavinir/hassio-onedrive-backup#16]
After upgrading to 2022.11.5, the onedrive backup sensors were unavailable.  The sensors were promptly restored after restarting the add-on.    Glad it was easily resolved, but wanted to share in case there is helpful information I can gather from the logs.

**Comment by lavinir** [comment]
Thanks. The sensors are refreshed every run interval for the addon. Possibly after the upgrade they were cleared for some reason. A restart of the addon is a way to force a new interval to run otherwise it would have likely sorted itself out in the next run.
In version 1.2 I'm reducing the refresh interval to every 5 minutes so things should happen much quicker.
