### ISSUE TITLE
App timeout after Installation

### ISSUE THREAD

**Issue by Frazior** [lavinir/hassio-onedrive-backup#163]
I installed V2.2.4 of the Add-On and restarted HA and am unable to get the Add-On to start. I have uninstalled and reinstalled all with the same issue. 
My HA install is as follows:

Intel 11th Gen NUC
Intel Celeron N4505
32GB RAM
512GB NVME HDD
Generic X836-64
Core   2024.1.2
Supervisor   2023.12.0
Operating System   11.3
Frontend   20240104.0

I pulled the following from the Add-In log-
    [1] Info: No new settings file. Attempting to restore from legacy configuration
    01/08/2024 16:03:11 [1] Info: Anonymous Telemetry Disabled
    01/08/2024 16:03:11 [1] Info: Backup interval configured to every 24 hours
    01/08/2024 16:03:11 [1] Warning: Token cache is empty
    01/08/2024 16:03:12 [7] Info: To sign in, use a web browser to open the page 
    https://microsoft.com/devicelogin and enter the code LDFNA8H6J to authenticate.

Reading the comments I went to the MS site (https://microsoft.com/devicelogin) and entered the code above and got a "That code didn't work. Check the code and try again." message

I reviewed the Supervisor logs and found the following error "24-01-08 16:05:10 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon OneDrive Backup to start, took more than 120 seconds" followed by the following:
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state running
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_ipv6_error/dns_server
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for trust/supervisor
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for docker_config/system
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for security/core
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for ipv4_connection_problem/system
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for pwned/addon
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for free_space/system
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for dns_server_failed/dns_server
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for multiple_data_disks/system
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.checks.base] Run check for no_current_backup/system
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.check] System checks complete
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state running
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state running
24-01-08 15:39:30 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
24-01-08 15:41:25 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
24-01-08 16:02:41 INFO (MainThread) [supervisor.addons.addon] Creating Home Assistant add-on data folder /data/addons/data/de91e161_hassio_onedrive_backup
24-01-08 16:02:41 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: de91e161_hassio_onedrive_backup
24-01-08 16:02:41 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/lavinir/amd64-hassonedrive with tag 2.2.4.
24-01-08 16:02:47 INFO (MainThread) [supervisor.addons.manager] Add-on 'de91e161_hassio_onedrive_backup' successfully installed
24-01-08 16:03:10 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on ghcr.io/lavinir/amd64-hassonedrive with version 2.2.4
24-01-08 16:03:10 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from de91e161_hassio_onedrive_backup
24-01-08 16:03:11 INFO (MainThread) [supervisor.api.middleware.security] /addons access from de91e161_hassio_onedrive_backup

Any help is appreciated and I donated for cofee in advance :)

**Comment by lavinir** [comment]
Appreciate the coffee but it's not a requirement for asking for help :)
Please try the following (for reference this is also explained in the readme [here](https://github.com/lavinir/hassio-onedrive-backup?tab=readme-ov-file#installation-instructions)
1. Restart the addon
2. Open the addon Web UI
3. You should have a banner on top asking you to authenticate with a code and a link. Complete this within a few minutes.

Make sure you have a successful login. Just a reminder this needs a Personal MS account (OneDrive for business is not supported).

**Comment by Frazior** [comment]
Thanks for the reply,

However, I can’t get the add-on to start so I can’t make it past step #1.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kissrac** [comment]
Hello Lavinir, 

This issue exists in my HA also, I just installed the addon and it doesnt start at all, however as you mentioned it seems running.
I am a bit confused because the Addon page shows a red circle as it was not running, but in the background backup completed and syncronized.
Also for sure the WebUI is not working for me...

Shall I upload something which can help you analyze this?

Thanks, 
kissrac

**Comment by lavinir** [comment]
Walk me through it. You install, then click start but you don't get any 'started' indication? 
What do you see when you try to open the WebUI?

Could you please share your logs ?

**Comment by kissrac** [comment]
Hi, 

Yes, I have installed it, tried to start the addon, but it is not starting.
If I try to start from the sidebar, it is just circling...
When I check the log I can see that I would need to authenticate, but I did that, that's why I mentioned that it seems to be running.
However no configuration possibility or on demand backup/restore...

Please find the logs below:
Add-on log:
OneDrive Backup
 [1] Info: No new settings file. Attempting to restore from legacy configuration
03/04/2024 14:09:05 [4] Info: Anonymous Telemetry Disabled
03/04/2024 14:09:05 [4] Info: Backup interval configured to every 24 hours
03/04/2024 14:09:05 [4] Warning: Token cache is empty
03/04/2024 14:09:08 [14] Info: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code LECCE6XF7 to authenticate.
03/04/2024 14:10:01 [11] Info: Creating new backup
03/04/2024 14:10:01 [11] Info: Starting full local backup
03/04/2024 14:10:06 [11] Info: Backup complete
03/04/2024 14:10:06 [11] Info: Found 1 backups to upload.
03/04/2024 14:10:06 [11] Info: Uploading hass_backup_2024-03-04-14-10 (03/04/2024 14:10:01)
03/04/2024 14:10:06 [11] Info: Fetching Local Backup (Slug:d6711cdd)
03/04/2024 14:10:06 [15] Info: Backup (d6711cdd) fetched successfully
03/04/2024 14:10:07 [11] Info: Starting file upload. (Size:32860160 bytes. Attempt: 1/3)
03/04/2024 14:10:13 [16] Info: Upload completed successfully


Supervisor log:
24-03-04 14:10:33 WARNING (MainThread) [supervisor.addons.addon] de91e161_hassio_onedrive_backup is already running!
24-03-04 14:11:04 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon OneDrive Backup to start, took more than 120 seconds
24-03-04 14:12:04 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon OneDrive Backup to start, took more than 120 seconds
24-03-04 14:12:33 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon OneDrive Backup to start, took more than 120 seconds

Thanks for checking it!

**Comment by lavinir** [comment]
Perhaps the banner is not showing up, could you please make sure [this](https://github.com/lavinir/hassio-onedrive-backup/tree/main?tab=readme-ov-file#html-content-filtering-error) isn't related ?

**Comment by kissrac** [comment]
After a while, the issue just fortunately got solved, however unfortunatel I dont know how or why... now everything works fine as expected 💯
