### ISSUE TITLE
[Feature request] Separate retention settings for full and partial backups

### ISSUE THREAD

**Issue by codemunkie15** [lavinir/hassio-onedrive-backup#178]
Hi

Would it be possible to have separate retention settings for full and partial backups? Or separate retention settings for backups created in HA vs the add-on?

I am currently using "Number of OneDrive backups" = 14 to keep 14 days of full daily backups but whenever an add-on is upgraded, it creates a partial backup that takes up one of my 14 retention slots.

Many thanks

**Comment by lavinir** [comment]
It's possible but I am always wary of having too many settings. Do you need those addon upgrade backups in OneDrive ? Because this could easily be solved by toggling on the 'Ignore Hass Upgrade Backups' option.

**Comment by codemunkie15** [comment]
> It's possible but I am always wary of having too many settings. Do you need those addon upgrade backups in OneDrive ? Because this could easily be solved by toggling on the 'Ignore Hass Upgrade Backups' option.

Perhaps not. I'd still want the full upgrade backup storing when HA Core is updated though. Does the Ignore Hass Upgrade Backups' option exclude those too?

**Comment by lavinir** [comment]
It does, yes. But consider you would still have that backup locally if you ignore it and while it won't be backed up to OneDrive you will still have the next backup triggered per your set schedule by the addon.

**Comment by MalteMatthey** [comment]
Hey @lavinir, I really wish there was an option for a "ignore partial backups" toggle switch. It would be perfect for this scenario. I’ve been dealing with a similar issue: I back up daily, and every time I update HA Core, it creates a large backup that’s retained indefinitely, which I then have to manually delete every few weeks.

Turning on "monitor all local backups" doesn’t quite work for me, as I don’t want the partial backups from add-on updates to count towards my local backups limit. I’d love to be able to ignore those, while still keeping the HA Core update backups.

**Comment by lavinir** [comment]
@MalteMatthey - Ignoring partial backups is a problem because of what I described in the beginning of the post (Just choosing to ignore your /media folder for example would make your backup "partial")
However, if your aim is to just ignore the automatic upgrade backups you have a toggle for this in the settings called "Ignore update backups"

**Comment by MalteMatthey** [comment]
@lavinir Thanks for your response!

I realize I wasn’t very clear about my issue, so let me explain further.

Since I only have 128GB of storage, I've limited myself to keeping just 3 backups locally. These are the challenges I'm facing:

1. If I don't monitor all local backups, I end up manually deleting update backups every few weeks, which is quite tedious.
2. If I choose to "ignore update backups" while monitoring all local backups, the issue persists since those update backups aren’t deleted automatically.
3. If I monitor all backups and opt not to "ignore update backups", there's a risk that no full backups remain on my local storage after updating 3 different addons (because this generates 3 partial backups).

The ideal solution would be to have an option to exclude partial backups from being monitored, or to introduce a "minimum number of full backups" setting as the original author suggested. This would allow for both "total number of local backups" and "minimum number of full backups" settings, where the first tracks all backups and the second ensures a certain number of full backups are always retained.
