### ISSUE TITLE
At which point in time will back-up run?

### ISSUE THREAD

**Issue by UweGrunewald** [lavinir/hassio-onedrive-backup#226]
Hi Lavinir, installed your famous add-on yesterday afternoon and "bought you a coffee", because I was so impressed and happy for this solution, since my previous one (via Fritz.Box NAS) stopped working.

When I installed and started the plugin, it created a back-up on my OneDrive :-)

I have an automation, that creates a full back-up each night at 01:00 and I thought, that the plugin will create one tonight as well. But there was/is non new on my OneDrive. When will the plugin run/create a back-up? I found no specification for that point in time in the plug-in's config.

Best, Uwe

**Comment by lavinir** [comment]
Hello @UweGrunewald ,

I'll try to explain but you should also check out the [Readme](https://github.com/lavinir/hassio-onedrive-backup) as it goes into details on what each of the settings do.

You cannot technically give the addon a 'backup schedule. The way it works is, you tell it is you set a 'backup interval'. It will make sure that there is a backup based on that interval so if you set if for 1 day, it will make sure there is a daily backup (24 hours since the last backup). 
You can modify this behavior further if you use "Generational Backups".

If you have your own automation to create backups, you should enable the "Monitor All Backups" option in the addon. The decision on what to keep locally and what to upload is determined by the "Max Backup" settings you set for OneDrive and Local. 

You can also prevent the backup logic  from running at certain hours by setting the 'Allowed Hours' setting - so that if you don't want these to occur at specific times.

Hope this helps.
