### ISSUE TITLE
Cannot open archive

### ISSUE THREAD

**Issue by tieskuh** [lavinir/hassio-onedrive-backup#30]
Hi,

I have a problem opening the backup in Windows. WinRAR/7-Zip/etc don't open the archive.
The same goes for all the other files within the main archive. I think it is because of the password protection. 
Might it be possible to make the password protection of the archive optional?

![image](https://user-images.githubusercontent.com/115901851/207413918-ab331372-decc-4a1a-b579-6c4c930263d1.png)
![image](https://user-images.githubusercontent.com/115901851/207413972-52a330e4-6142-4b70-9e2d-32845ee53b63.png)
![image](https://user-images.githubusercontent.com/115901851/207414033-099f9ffe-5332-46bd-bfeb-72db510ce2d4.png)

Regards,
Matthijs

**Comment by lavinir** [comment]
Yes it's because it is password protected. I'm reluctant to make this optional since it cannot be "on by default" because there is not default value for a password. This way most users will likely not think about it. 

What is the use case for what you're trying to do ? Restoring the backup will work fine in Home Assistant when supplying the password. 
If you still **need** to extract it outside of a backup restore you can use a python script for this. See [this](https://community.home-assistant.io/t/get-files-from-password-protected-snapshot/245066/17) post.

**Comment by tieskuh** [comment]
Sometimes when I mess up a file for example I just want to restore a single file. With password it makes it hard to open it in Windows. Just an idea: maybe an extra option disable_password which defaults to false?

**Comment by lavinir** [comment]
Yes I considered that. I'll think about how best to address this in a future update

**Comment by Nicwalle** [comment]
+1 for the ability to make the password optional. Having the ability to use one is great but it can in fact be very annoying if you don't want to have a password for your snapshot.
Thanks for the potential update

**Comment by lavinir** [comment]
This is now possible in the latest release (1.4)

**Comment by tieskuh** [comment]
> This is now possible in the latest release (1.4)

Great! Many thanks.
