### ISSUE TITLE
Option "recovery mode" does not exist in the schema  for onedrive backup

### ISSUE THREAD

**Issue by willem-ebbers** [lavinir/hassio-onedrive-backup#66]
Hi,

I have been running Onedrive for a couple of weeks now, and I just noticed that my supervisor is showing below error message every couple minutes or so:

`23-03-23 15:17:53 WARNING (MainThread) [supervisor.addons.options] Option 'recovery_mode' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)`

![image](https://user-images.githubusercontent.com/60136106/227233212-5f5536bf-d6ab-41b9-831a-e5b5c29e3f69.png)

I am running the latest version of Onedrive Backup, in which the recovery mode has been removed. so I do understand the error message.
However is/can there something (be) done to fix this error from showing, either on my installation or by the next update?
(I notice glances is also showing an error...

**Comment by lavinir** [comment]
Hi,

This is a side effect of the removal of the recovery_mode config option. Since you upgraded it keeps the old config. 
You can just go to the addo nconfiguration , click the 3 dots at the top right and choose "edit yaml" and just remove the line from the config and you should be good to go with no more warnings.

**Comment by willem-ebbers** [comment]
I did suspect something like that, just didn't know where to find it.

Thanks for pointing me where to fix it.
