### ISSUE TITLE
Custom Onedrive backup folder

### ISSUE THREAD

**Issue by Salvora** [lavinir/hassio-onedrive-backup#77]
Hello,

Is there a way to backup to custom folder?

**Comment by Yngve0** [comment]
Would be very usefull since I have multiple HASS-installations.

**Comment by lavinir** [comment]
@Salvora, This is by design. Onedrive allows a specific permission scope for apps that only grant access to their own folder, the location cannot be changed. The alternative would be to request permissions to your entire OneDrive meaning read / write on all folders which is a non starter for me.

@Yngve0, multiple HA installations are fully supported via the [Instance name](https://github.com/lavinir/hassio-onedrive-backup#backup-instance-name-optional) option.

**Comment by Salvora** [comment]
I see thanks for the explanation. I guess I have to stick with it.
