### ISSUE TITLE
Supervisor Logs - Option 'sync_interval_hours' does not exist in the schema for OneDrive Backup

### ISSUE THREAD

**Issue by ziptbm** [lavinir/hassio-onedrive-backup#81]
`23-04-12 12:47:20 WARNING (MainThread) [supervisor.addons.options] Option 'sync_interval_hours' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)`

HA 2023.4.2 and OneDrive Backup 2.1.1.

My HA instance appears to be rebooting every 15 minutes and has been doing so for the past hour with no clear reason why.  I do however see the warning above repeatedly in the Supervisor logs.

**Comment by lavinir** [comment]
That setting was removed in version 1.2. The warnings in the supervisor logs are because it still exists in your yaml.
You can just go to the addon configuration and edit the yaml to remove it - that should clear the warnings.

Anyway, that wouldn't be why your HA is restarting so can't help you on that front I'm afraid :)
